workflow "Storybook" {
  on = "push"
  resolves = ["Publish Storybook to Surge.sh"]
}

action "Publish Storybook to Surge.sh" {
  uses = "codeship/storybook-surge-github-action@0.0.1"
  secrets = [
    "SURGE_LOGIN",
    "SURGE_TOKEN",
    "GITHUB_TOKEN",
  ]
}
